quarkus.index-dependency.rimfrost-framework-regel-komplettering.group-id=se.fk.rimfrost.framework.regel.komplettering
quarkus.index-dependency.rimfrost-framework-regel-komplettering.artifact-id=rimfrost-framework-regel-komplettering

quarkus.index-dependency.rimfrost-referensdata-erbjudande.group-id=se.fk.rimfrost.referensdata
quarkus.index-dependency.rimfrost-referensdata-erbjudande.artifact-id=rimfrost-referensdata-erbjudande
