quarkus.index-dependency.rimfrost-framework-regel-komplettering.group-id=se.fk.rimfrost.framework.regel.komplettering
quarkus.index-dependency.rimfrost-framework-regel-komplettering.artifact-id=rimfrost-framework-regel-komplettering

quarkus.index-dependency.rimfrost-referensdata-erbjudande.group-id=se.fk.rimfrost.referensdata
quarkus.index-dependency.rimfrost-referensdata-erbjudande.artifact-id=rimfrost-referensdata-erbjudande

# Container image configuration
quarkus.container-image.name=rimfrost-regel-rtf-manuell-komplettering

# Kafka setup
kafka.source=RegelRtfManuellKomplettering
kafka.subtopic=rtf-manuell-komplettering
quarkus.kafka.devservices.topics=rtf-manuell-komplettering-requests,rtf-manuell-komplettering-responses,operativt-uppgiftslager-status-notification

#Incoming
mp.messaging.incoming.regel-requests.topic=rtf-manuell-komplettering-requests
#mp.messaging.incoming.operativt-uppgiftslager-status-notification.topic=operativt-uppgiftslager-status-notification.rtf-manuell-komplettering

#Outgoing
mp.messaging.outgoing.regel-responses.topic=rtf-manuell-komplettering-responses

# Persistence
quarkus.flyway.default-schema=regel_rtf_manuell_komplettering
regel.persistence.table-prefix=rtf_manuell_komplettering
quarkus.hibernate-orm.packages=se.fk.rimfrost.framework.regel.storage.internal,se.fk.rimfrost.framework.regel.logic.storage.internal,se.fk.rimfrost.framework.regel.oul.storage.internal

%prod.quarkus.datasource.username=${DB_USERNAME}
%prod.quarkus.datasource.password=${DB_PASSWORD}
%prod.quarkus.datasource.jdbc.url=${DB_URL}

# REST setup
oul.api.base-url=http://rimfrost-k8s-uppgiftslager:8080
referensdata.api.base-url=http://rimfrost-k8s-referensdata:8080